version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:9.6.23-buster
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  backend:
    build: back_end
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: front_end
    ports:
      - "3000:3000"
    depends_on:
      - backend