# Generated by Django 3.2.7 on 2021-09-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210909_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='name',
            new_name='code',
        ),
    ]
