# Generated by Django 3.2.7 on 2021-09-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_name_discount_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
