# Generated by Django 3.2.7 on 2021-09-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210923_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.basket'),
        ),
    ]
