# Generated by Django 3.2.7 on 2021-09-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customermodel_phone'),
        ('order', '0006_alter_basket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel'),
            preserve_default=False,
        ),
    ]
