# Generated by Django 3.2.7 on 2021-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_basket_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.FloatField(default=None),
        ),
    ]
