# Generated by Django 3.2.7 on 2021-09-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='phone',
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='postal_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
