# Generated by Django 3.2.7 on 2021-09-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210906_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.addressmodel'),
        ),
    ]
