# Generated by Django 3.2.7 on 2021-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_discountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='phone',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
