# Generated by Django 3.2.7 on 2021-09-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
