# Generated by Django 3.2.7 on 2021-09-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='reset_password_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
